# os:
#   - linux
# sudo: required
# addons:
#   apt:
#     # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
#     sources:
#       - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
#     packages:
#       - libstdc++6
#       - fonts-droid-fallback
#       - lib32stdc++6
#       - curl
#
# before_script:
#   - git clone https://github.com/flutter/flutter.git -b beta
#   - ./flutter/bin/flutter doctor
# script:
#   #- ./flutter/bin/flutter test
# cache:
#   directories:
#     - $HOME/.pub-cache

language: dart
dist: xenial
addons:
  apt:
    packages:
      - libstdc++6
      - fonts-droid-fallback
      - lib32stdc++6
      - curl
install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$PATH:pwd/flutter/bin/"
  - ./flutter/bin/flutter doctor
script:
  # - ./flutter/bin/flutter test
  - cd spotiseven
  - pwd
  - flutter -v build apk
cache:
  directories:
    - $HOME/.pub-cache
