# os:
#   - linux
# sudo: required
# addons:
#   apt:
#     # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
#     sources:
#       - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
#     packages:
#       - libstdc++6
#       - fonts-droid-fallback
#       - lib32stdc++6
#       - curl
#
# before_script:
#   - git clone https://github.com/flutter/flutter.git -b beta
#   - ./flutter/bin/flutter doctor
# script:
#   #- ./flutter/bin/flutter test
# cache:
#   directories:
#     - $HOME/.pub-cache

os: linux
language: android
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - sys-img-armeabi-v7a-google_apis-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
jdk: oraclejdk8
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback
      # - lib32stdc++6
      # - curl
install:
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip -qq gradle-3.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH="$PATH:$(pwd)/flutter/bin/"
  - ./flutter/bin/flutter doctor
script:
  # - ./flutter/bin/flutter test
  - cd spotiseven
  - flutter pub get
  - flutter pub upgrade
  - flutter -v build apk
cache:
  directories:
    - $HOME/.pub-cache
